# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  #- x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\isis_nexus_streamer

# scripts that run after cloning repository
#install:
#  - ps: cd C:\projects\isis_nexus_streamer\ci
#  - ps: .\appveyor_install.ps1

# scripts to run before build
before_build:
  - cmd: cd C:\projects
  - cmd: md isis_nexus_streamer-build
  - cmd: cd isis_nexus_streamer-build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..\isis_nexus_streamer

#build: off
build:
  project: C:\projects\isis_nexus_streamer-build\isis_nexus_streamer.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: detailed                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off
#test_script:
#  - cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure

